spring:
  application:
    name: SB-app-with-Mysql
  datasource:
    url: jdbc:mysql://mysqldb:3306/SBMS
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
