spring:
  application:
    name: SB-app-with Mysql
  datasource:
    url: jdbc:mysql://localhost:3306/project
    username: root
    password: Gaurav@123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
