spring:
  application:
    name: SB-app-with Mysql
  datasource:
    url: jdbc:mysql://mysqldb:3306/project
    username: root
    password: Gaurav@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create